### ISSUE TITLE
Check if silver counts as ColorSensor.GRAY

### ISSUE THREAD

**Issue by Miezekatze64** [pinjuf/kurzschliesser-ev3dev#3]
Check if ColorSensor.GRAY can identify the silver line, which indicates the beginning of the evacuation area, to avoid the robot to drive back out of the zone.

**Comment by pinjuf** [comment]
1) fuk u
2) we re waiting for some alufolie
3) ColorSensor.GRAY does not exist

**Comment by pinjuf** [comment]
this is no longer needed because of the ongoing development of rgb reading, for which you @Miezekatze64 are responsible for. just saying
